version: '3.7'
services:
  shop-mongo:
    image: mongo:latest
    container_name: shop-mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
  # shop-pos-backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile 
  #   container_name: shop-pos-backend
  #   ports:
  #     - 8080:80
  #   restart: always
  #   depends_on:
  #     - shop-mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}